"""Git Hooks management for Python projects."""

__all__ = ["install_hooks", "uninstall_hooks", "list_hooks"]

import json
import stat
from typing import Any, Dict, List
from .common import ROOT_DIR, run_command


GITHOOKS_CONFIG = ROOT_DIR / ".githooks.json"
GITHOOKS_DIR = ROOT_DIR / ".githooks"
GIT_HOOKS_DIR = ROOT_DIR / ".git" / "hooks"

SUPPORTED_HOOKS = [
    "applypatch-msg",
    "pre-applypatch",
    "post-applypatch",
    "pre-commit",
    "pre-merge-commit",
    "prepare-commit-msg",
    "commit-msg",
    "post-commit",
    "pre-rebase",
    "post-checkout",
    "post-merge",
    "pre-push",
    "pre-receive",
    "update",
    "post-receive",
    "post-update",
    "reference-transaction",
    "push-to-checkout",
    "pre-auto-gc",
    "post-rewrite",
    "sendemail-validate",
    "fsmonitor-watchman",
    "p4-changelist",
    "p4-prepare-changelist",
    "p4-post-changelist",
    "p4-pre-submit",
    "post-index-change",
]


def load_config() -> Dict[str, Any]:
    """Load Git hooks configuration from .githooks.json."""
    if not GITHOOKS_CONFIG.exists():
        return {}

    try:
        with open(GITHOOKS_CONFIG, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error loading .githooks.json: {e}")
        return {}


def save_config(config: Dict[str, Any]) -> bool:
    """Save Git hooks configuration to .githooks.json."""
    try:
        with open(GITHOOKS_CONFIG, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2, ensure_ascii=False)

        return True
    except IOError as e:
        print(f"Error saving .githooks.json: {e}")

        return False


def get_hook_script(hook_name: str, actions: List[str]) -> str:
    """Generate a Git hook script that executes the configured actions."""
    script_lines = [
        "#!/usr/bin/env python3",
        "",
        '"""',
        f"Git hook: {hook_name}",
        "Auto-generated by Git Hooks manager",
        '"""',
        "",
        "import sys",
        "import subprocess",
        "from pathlib import Path",
        "",
        "# Get the project root directory",
        "ROOT_DIR = Path(__file__).parent.parent.parent",
        "",
        "# Change to project root",
        "import os",
        "os.chdir(ROOT_DIR)",
        "",
        "# Execute configured actions",
        "failed = False",
        "",
    ]

    for action in actions:
        script_lines.append(f'    print("Running: {action}")')
        script_lines.append(f'    result = subprocess.run("{action}", shell=True)')
        script_lines.append("    if result.returncode != 0:")
        script_lines.append("        failed = True")
        script_lines.append("")

    script_lines.extend(
        [
            "if failed:",
            '    print("\\n❌ Git hook failed. Please fix the errors above.")',
            "    sys.exit(1)",
            "",
            'print("\\n✅ Git hook passed!")',
        ]
    )

    return "\n".join(script_lines)


def create_hook_file(hook_name: str, actions: List[str]) -> bool:
    """Create a Git hook file in .git/hooks/."""
    if not GIT_HOOKS_DIR.exists():
        print(f"Error: {GIT_HOOKS_DIR} does not exist. Is this a Git repository?")

        return False

    hook_file = GIT_HOOKS_DIR / hook_name
    script_content = get_hook_script(hook_name, actions)

    try:
        with open(hook_file, "w", encoding="utf-8") as f:
            f.write(script_content)

        hook_file.chmod(hook_file.stat().st_mode | stat.S_IEXEC)
        print(f"✅ Installed hook: {hook_name}")

        return True
    except IOError as e:
        print(f"Error creating hook {hook_name}: {e}")

        return False


def remove_hook_file(hook_name: str) -> bool:
    """Remove a Git hook file from .git/hooks/."""
    hook_file = GIT_HOOKS_DIR / hook_name

    if not hook_file.exists():
        return True  # Already removed

    try:
        hook_file.unlink()
        print(f"✅ Removed hook: {hook_name}")

        return True
    except IOError as e:
        print(f"Error removing hook {hook_name}: {e}")

        return False


def install_hooks() -> bool:
    """Install Git hooks based on .githooks.json configuration."""
    if not GIT_HOOKS_DIR.exists():
        print(f"Error: {GIT_HOOKS_DIR} does not exist. Is this a Git repository?")

        return False

    config = load_config()

    if not config:
        print("No hooks configuration found in .githooks.json")
        print("Create a .githooks.json file to configure hooks.")
        return False

    print("Installing Git hooks...")
    success = True

    for hook_name, hook_config in config.items():
        if hook_name not in SUPPORTED_HOOKS:
            print(f"⚠️  Warning: Unknown hook '{hook_name}' (skipping)")
            continue

        if not isinstance(hook_config, dict):
            print(f"⚠️  Warning: Invalid configuration for '{hook_name}' (skipping)")
            continue

        enabled = hook_config.get("enabled", True)
        if not enabled:
            print(f"⏭️  Skipping disabled hook: {hook_name}")
            continue

        actions = hook_config.get("actions", [])

        if not actions:
            print(f"⚠️  Warning: No actions configured for '{hook_name}' (skipping)")
            continue

        if not isinstance(actions, list):
            print(f"⚠️  Warning: Invalid actions format for '{hook_name}' (skipping)")
            continue

        if not create_hook_file(hook_name, actions):
            success = False

    if success:
        print("\n✅ All hooks installed successfully!")
    else:
        print("\n⚠️  Some hooks failed to install.")

    return success


def uninstall_hooks() -> bool:
    """Uninstall all Git hooks."""
    if not GIT_HOOKS_DIR.exists():
        print(f"Error: {GIT_HOOKS_DIR} does not exist. Is this a Git repository?")

        return False

    config = load_config()

    if not config:
        print("No hooks configuration found in .githooks.json")

        return False

    print("Uninstalling Git hooks...")
    success = True

    for hook_name in config.keys():
        if hook_name not in SUPPORTED_HOOKS:
            continue

        if not remove_hook_file(hook_name):
            success = False

    if success:
        print("\n✅ All hooks uninstalled successfully!")
    else:
        print("\n⚠️  Some hooks failed to uninstall.")

    return success


def list_hooks() -> None:
    """List all configured Git hooks."""
    config = load_config()

    if not config:
        print("No hooks configuration found in .githooks.json")
        return

    print("Configured Git hooks:")
    print()

    for hook_name, hook_config in config.items():
        if hook_name not in SUPPORTED_HOOKS:
            print(f"  ⚠️  {hook_name} (unknown hook)")
            continue

        if not isinstance(hook_config, dict):
            print(f"  ⚠️  {hook_name} (invalid configuration)")
            continue

        enabled = hook_config.get("enabled", True)
        status = "✅ enabled" if enabled else "⏭️  disabled"
        actions = hook_config.get("actions", [])
        print(f"  {status} {hook_name}")

        if actions:
            for action in actions:
                print(f"    → {action}")
        else:
            print("    (no actions configured)")
        print()
