name: Run Unit Tests

on:
  workflow_call:
    inputs:
      packages:
        type: string
        description: 'JSON array of package names to test (e.g. ["cpf-val","cnpj-dv"])'
        required: true
      python-versions:
        type: string
        description: 'JSON array of Python versions (e.g. ["3.10","3.11","3.12","3.13","3.14"])'
        required: true
      max-parallel:
        type: number
        description: 'Maximum number of parallel jobs'
        required: false
        default: 5
      api-url:
        type: string
        description: 'BR Utils API URL'
        required: true
    secrets:
      api-token:
        description: 'BR Utils API token'
        required: false

permissions:
  contents: read

jobs:
  test:
    name: Tests `${{ matrix.package }}` in Python v${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: ${{ inputs.max-parallel }}
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
        package: ${{ fromJSON(inputs.packages) }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ runner.os }}-python-test-${{ matrix.package }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt', 'requirements-dev.txt', format('packages/{0}/pyproject.toml', matrix.package)) }}
          path: ~/.cache/pip

      - run: python -m pip install --upgrade pip
      - run: python require

      - run: python run test ${{ matrix.package }}
        env:
          API_URL: ${{ inputs.api-url }}
          API_TOKEN: ${{ secrets.api-token }}
